### ISSUE TITLE
Planned Features.

### ISSUE THREAD

**Issue by L0um15** [L0um15/SpotiSharp#1]
**Subscribe to this event to keep track of incomming changes**
### Finished
- [x] Rewrite
- [x] Configuration Rework
- [x] Linux Support
- [x] Albums Support
- [x] Playlist Support
- [x] Lyrics Support
- [x] Spotify URL Support
- [x] Metadata (Artist's, Album Art, Lyrics, etc.)
- [x] Check Version

**Comment by L0um15** [comment]
All goals has been reached, Moving from alpha to full release

**Comment by L0um15** [comment]
Thinking about linux support 🤔
But that means reverting to .NET Core 3.1 which means increased file size.

**Comment by L0um15** [comment]
Current state of SpotiSharp Linux port: 
![obraz](https://user-images.githubusercontent.com/44427021/99578864-b704fa00-29dd-11eb-91fa-62220fe29b64.png)
Seems to work fine but i discovered few issues so far. Working on it :)

**Comment by L0um15** [comment]
Linux port seems to be finished. Update will be released shortly after few test's (Yes this is album support) :) 
![obraz](https://user-images.githubusercontent.com/44427021/99853017-7abece80-2b82-11eb-905e-49964350281f.png)

**Comment by L0um15** [comment]
Thinking about new config options like:
 - Ability to change ffmpeg location.
 - Change default download location.
 - More? (Start new issue)

**Comment by evgeniy702** [comment]
where 320 kbps? i have premium on my account!

**Comment by L0um15** [comment]
> 
> 
> where 320 kbps? i have premium on my account!

Spotify disallows downloading music from their servers to be used outside Spotify Application.
Also every track downloaded from their servers is in ogg format which needs to be converted to be used. Which means worse bitrate
SpotiSharp uses Spotify Search API to merge metadata (lyrics, albums, cover arts) from their servers to downloaded track from Youtube (like every software that claims to be the one and the only one). Also SpotiSharp does not require premium to be used.
Im very sorry that my application made you disappointed. Im working very hard to make everyone enjoy using this software. If you have any feature request please create new issue on issue tracker.

**Comment by L0um15** [comment]
Configuration rework which is being worked on, will be incompatible with current config file!
But dont worry, Configuration rework includes automatic config updating!
New release should arrive in few days. I need to check for all issues before release.

**Comment by cristiMiomni** [comment]
The playlist retrieved has only max 100 items. I know this is an intended behavior by Spotify but cannot add offset to get the whole playlist not just the first 100 tracks

**Comment by L0um15** [comment]
Hi, @cristiMiomni. Please create new issue in issue tracker.
**Planned Features** was created for monitoring progress of SpotiSharp.
Here you can ask about progress of incomming features.
Provide detailed information of what the issue is. (Templates are available.)
All **off-topic** comments will be **deleted**.

**Comment by L0um15** [comment]
Configuration Rework will be finished this week.
Right after rework i will focus on better colored logging.
![obraz](https://user-images.githubusercontent.com/44427021/101943102-d7922f80-3bea-11eb-999e-811c399b5f0e.png)

**Comment by L0um15** [comment]
Changed my mind. 
Instead of colored console logging i will focus on file logger.

**Comment by L0um15** [comment]
Closing due to long term inactivity
