### ISSUE TITLE
Replace invalid characters for the file system

### ISSUE THREAD

**Issue by Deyvan** [L0um15/SpotiSharp#3]
![изображение](https://user-images.githubusercontent.com/51455765/99151662-d33b2b00-26ad-11eb-8085-ebab4e2d498f.png)

**Comment by L0um15** [comment]
Im aware of this issue but i dont see which line caused this problem.
Im gonna assume that this NullReferenceException is caused when no lyrics were found.
I already fixed that in [feature_playlistsupport](https://github.com/L0um15/SpotiSharp/tree/feature_playlistsupport) branch. 
I would like to know which song you were trying to download.
"keyboard input" or Spotify URL if possible, so i can investigate it.

**Comment by Deyvan** [comment]
``https://open.spotify.com/track/4AtdXNdk912SPC3037pwBp?si=4XjXp45nQPCyb9GqM7YdtQ``
All the forbidden ones I know ``<>:"/\|?*``

**Comment by L0um15** [comment]
Fixed it about 15 minutes ago :). I will search for remaining bugs.
New release should be uploaded before 20:00 GMT+1
![obraz](https://user-images.githubusercontent.com/44427021/99188664-6c754a80-275d-11eb-9be2-710c168d5f01.png)
