### ISSUE TITLE
No arguments provided. Awaiting for input

### ISSUE THREAD

**Issue by ghost** [L0um15/SpotiSharp#30]
**Describe the bug**
App not running

**How To Reproduce**
Open up the exe

**Screenshots**
![image](https://user-images.githubusercontent.com/71657811/204353689-9f66e67c-a048-410f-ab69-2d6404ebdd0f.png)

**Include latest log file**
[log-20221128182635.txt](https://github.com/L0um15/Spotisharp/files/10106510/log-20221128182635.txt)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - OS Version: OS Build 19044.2251 Version 21H2

**Comment by L0um15** [comment]
You have opened spotisharp via double-clicking exe, this is expected behaviour.
Spotisharp simply waits for your keyboard input so you can type for example `sonic frontiers undefeatable` and press enter.


This is not a bug, please read Readme.md for further instructions.

**Comment by Someone-Somwhere** [comment]
> You have opened spotisharp via double-clicking exe, this is expected behaviour. Spotisharp simply waits for your keyboard input so you can type for example `sonic frontiers undefeatable` and press enter.
> 
> This is not a bug, please read Readme.md for further instructions.

Do I type it into the command line.
