### ISSUE TITLE
Wrong songs or wrong durations

### ISSUE THREAD

**Issue by djcenk** [L0um15/SpotiSharp#36]
Hi 
Sometimes gets songs downloaded from Spotify wrong, or calculates the duration incorrectly. 
Sometimes it's 11 minutes, sometimes 20 seconds.
This happens especially with large playlists.
Thanks

**Comment by L0um15** [comment]
Hi, thanks for bug report. Can you paste here a link to the given playlist? And specify which songs are downloaded incorrectly.

**Comment by djcenk** [comment]
Hi,
https://open.spotify.com/playlist/37i9dQZF1DXd8Yptw1g5FC
Emre Aydın - Firtinam
JP Saxe - I Don't Miss You
Henry Moodie - eighteen
[https://prnt.sc/G9zdILnlxh5x](url)
[https://prnt.sc/Aq04sLV7538L](url)
thank you

**Comment by L0um15** [comment]
Ah yes im aware of this issue. Spotisharp heavely relies on scraping contents from websites which is not accurate as much as i want it to be, especially less known or newer songs. Working on the solution.

**Comment by djcenk** [comment]
> Ah yes im aware of this issue. Spotisharp heavely relies on scraping contents from websites which is not accurate as much as i want it to be, especially less known or newer songs. Working on the solution.

Hello. 
Has this bug been resolved yet? 
I would be very happy if it can be solved
I use Spotisharp all the time.
Thank You

**Comment by L0um15** [comment]
Not yet, i don't have much time lately. But starting from sunday i will be more active :)

**Comment by L0um15** [comment]
> I would be very happy if it can be solved

I think that the best way to do this is to implement "score system" that will match title similiarity, and measure average time of all search results. Now i have a glimpse of what need to be done. Like i said i will get to work in this weekend

**Comment by L0um15** [comment]
I just wrote basic score system that checks for string similiarity and average time of the tracks. Results are quite good, but not perfect. I still have to test it. Oh and you can try again to download those tracks using current version of Spotisharp, 3 weeks passed so you can give it a try and see if they are now downloading correctly.

![Zrzut ekranu 2023-04-21 235413](https://user-images.githubusercontent.com/44427021/234075090-a9d636ea-2d19-4afc-beea-c0274d1ff8fa.png)

**Comment by djcenk** [comment]
Thanks for your work, the first checks look good. I will examine it in detail and give information.

**Comment by djcenk** [comment]
Hi, 
I observed that he never downloaded the song linked below.
[https://open.spotify.com/track/1V3mUG5cCiE8OwDFJLulwW?si=89160222a5a34db1](url)

**Comment by L0um15** [comment]
This song is not present in your playlist. Try to download this track by url or searching it by text.

**Comment by djcenk** [comment]
Hello again. 
Unfortunately, there are still incorrect downloads of new songs.I can tell this problem by the duration of the song.
[https://open.spotify.com/track/0DvI4mAIPFU81A07MLhJme?si=6ede485e33184f24](url)
This song duration has 2:06 but downloaded another song and duration 4:17 

Downloaded track : [https://www.youtube.com/watch?v=CupjSafuR30](url)
this is a very irrelevant result, how can i disable youtube search and download ? 

thanks 
Cenk

**Comment by L0um15** [comment]
> Unfortunately, there are still incorrect downloads of new songs.I can tell this problem by the duration of the song.

I can't do much about it. Spotisharp is just a mediator between spotify and youtube that downloads songs from youtube and injects metadata from spotify and its partner musixmatch (lyrics). Search syntax mostly looks like (author - title) "Serena - Playa" and this phrase is used during search. I guess you'll have to wait until this song gets more recognision on youtube or try different solution. I personally recommend using "[youtube-dlp](https://github.com/yt-dlp/yt-dlp)" however you won't be able to sync this with your spotify account thus there will be no metadata and lyrics available to download.

> this is a very irrelevant result, how can i disable youtube search and download ?

Sorry, can't do this. Its a core of application. Disabling it would defeat whole purpose.


Feel free to reopen it if you have more questions.
