### ISSUE TITLE
SpotifyAPI needs to reference the latest release

### ISSUE THREAD

**Issue by narutoshocker** [L0um15/SpotiSharp#44]
**Describe the bug**
Currently spotisharp doesn't work. Spotify updated the variable types and it's causing chaos on the SpotifyAPI side.
They fixed it, but we need to update to 7.1.1 here
https://github.com/L0um15/Spotisharp/blob/dev/Spotisharp.Client/Spotisharp.Client.csproj

The version:
https://github.com/JohnnyCrazy/SpotifyAPI-NET/releases/tag/7.1.1

The issue resolved:
https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/942

**How To Reproduce**
try to download ANY song or playlist
https://open.spotify.com/track/6M7oa01tpOccJXkb9rUoH8?si=3963e586598643df

[log-20240308223014.txt](https://github.com/L0um15/Spotisharp/files/14544778/log-20240308223014.txt)

**Comment by L0um15** [comment]
Thanks for your help. I'll take a look at it.

**Comment by Lewis-Fam** [comment]
My apologies.  JSON errors resolved and referenced updated in pull 942: https://github.com/JohnnyCrazy/SpotifyAPI-NET/pull/942

**Comment by L0um15** [comment]
Thanks! Update merged. Closing now.
