### ISSUE TITLE
Musixmatch returns 404 while fetching lyrics

### ISSUE THREAD

**Issue by L0um15** [L0um15/SpotiSharp#47]
tested these changes on my local branch and was able to download files (originally this would crash on any file attempt)
Note: noticed that the following error output exists (happens at the end of the download, so the file still exists and works fine):

```
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Spotisharp.Client.Services.MusixmatchService.SearchLyricsFromText(String query) in E:\Coding\Repos\Spotisharp.Client\Services\MusixmatchService.cs:line 14
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__0>d.MoveNext() in E:\Coding\Repos\Spotisharp.Client\Program.cs:line 280
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in E:\Coding\Repos\Spotisharp.Client\Program.cs:line 132
   at Program.<Main>(String[] args)
```

_Originally posted by @narutoshocker in https://github.com/L0um15/Spotisharp/issues/45#issuecomment-2023751482_

**Comment by L0um15** [comment]
Due to recent changes in musixmatch website layout, scraping data became much more challenging. Website seems to be rendered by using javascript and this change made parsing raw html data via HTMLAgilityPack near impossible without any sort of JS engine. It was inevitable and solution needs to be found.

**Comment by Lewis-Fam** [comment]
I fixed this in my fork.  However, build test is failing because I replaced the SpotifyAPI nuget with git clone of the SpotifyAPI repository. Therefore, I am not going to submit a pull request.  Also, a few customizations (check for dups, batch runner, etc.) that I am too lazy to branch and remove.

Here is the solution:

Edit File: Spotisharp.Client/Services/MusixmatchService.cs

Replace Line 14: 
`string response = await client.GetStringAsync(searchQuery);`

with

```
 var responseMessage = await client.GetAsync(searchQuery);
            if (!responseMessage.IsSuccessStatusCode)
                return string.Empty;

            var response = await responseMessage.Content.ReadAsStringAsync();
```

**Comment by Lewis-Fam** [comment]
A second solution.  Remove the lyrics task.

I don't have the line numbers because my Program.cs is modified.

In Program.cs:

Comment out: 
`Task<string> lyricsTask = MusixmatchService.SearchLyricsFromText(fullName);`

and

`file.Tag.Lyrics = await lyricsTask;`

**Comment by L0um15** [comment]
I got around this by temporarily disabling the musixmatch service. Thanks. Closing.
