### ISSUE TITLE
Unhandled exception. System.FormatException: String '2014' was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by faroukmok** [L0um15/SpotiSharp#5]
Hi,
i have a Exception during downloading a playlist

playlist  : https://open.spotify.com/playlist/37i9dQZF1E4yHPIesfGpbT
Song :  Muhammad Al Muqit - The Way of the Tears

![image](https://user-images.githubusercontent.com/22342496/101141712-f99d1800-3614-11eb-9312-e19803c4dc6f.png)

 - OS: [Windows]
- OS Version [Win 10] (Windows)

**Comment by L0um15** [comment]
Most Spotify tracks has date provided in full format like 04.12.2020.
This specyfic track has only year provided and here it throws invalid DateTime exception.
Working on it.

**Comment by L0um15** [comment]
Fixed it.
I will release it shortly.
![obraz](https://user-images.githubusercontent.com/44427021/101154700-5c4adf80-3626-11eb-99ae-c1021d139a5a.png)

**Comment by faroukmok** [comment]
Done thanks bro.
