### ISSUE TITLE
Will work only for playlist with at most 100 tracks

### ISSUE THREAD

**Issue by cristiMiomni** [L0um15/SpotiSharp#6]
**Describe the bug**
SpotiSharp will retrieve only first 100 tracks from a playlist which might have more than 100. The reason is Spotify API pagination and I think it should be added (maybe using PaginateAll from SpotifyAPI.Web)

**How To Reproduce**
Any playlist with more than 100 tracks
 
 
**Desktop (please complete the following information):**
- Windows 10 
- build 10.0.19042

**Comment by L0um15** [comment]
Definitely i'll have to look into it.

Here is a workaround which can be used until solution is found.
In spotify application you can select tracks with ctrl.
Just like in any file manager application you can copy and paste them to newly created playlist using keyboard shortcuts.
Make 2 temporary playlists and split tracks between them.

**Comment by L0um15** [comment]
Added pagination and it seems to work correctly 
I have to make few checks before releasing it.

![obraz](https://user-images.githubusercontent.com/44427021/101622091-e88a4780-3a16-11eb-8e51-b3a038fd3737.png)

![obraz](https://user-images.githubusercontent.com/44427021/101622259-1b344000-3a17-11eb-810c-105bdaf853f1.png)

**Comment by cristiMiomni** [comment]
> Definitely i'll have to look into it.
> 
> Here is a workaround which can be used until solution is found.
> In spotify application you can select tracks with ctrl.
> Just like in any file manager application you can copy and paste them to newly created playlist using keyboard shortcuts.
> Make 2 temporary playlists and split tracks between them.

Already did that, thanks for suggestion. I am mostly interested to see how you implemented pagination (I tried myself to do it on your code with with no luck)

**Comment by L0um15** [comment]
Here is solution:
![obraz](https://user-images.githubusercontent.com/44427021/101626225-f04cea80-3a1c-11eb-8053-f0a276f086c8.png)

**Comment by L0um15** [comment]
It won't stop :)
![obraz](https://user-images.githubusercontent.com/44427021/101626938-ed062e80-3a1d-11eb-99a1-752a86dae922.png)

**Comment by cristiMiomni** [comment]
Thanks a lot

**Comment by L0um15** [comment]
I considered this issue as solved. If any issues occurs feel free to re-open this issue.
Also don't forget to leave a star if you like SpotiSharp so others can find this repository :)
